// <auto-generated />
using System;
using GakhoProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GakhoProject.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20231105230255_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GakhoProject.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("PartiesName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("YourFullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1792, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PartiesName = "ForGeo",
                            YourFullName = "tamta grigolia"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1792, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PartiesName = "Georgia dream",
                            YourFullName = "irakli kobaxidze"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1792, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PartiesName = "ForGeo",
                            YourFullName = "giorgi gaxaria"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
